### ISSUE TITLE
Invalid class in Bolt 3.1.2 - 3.2.1

### ISSUE THREAD

**Issue by peterboorsma** [xiaohutai/bolt-relatedcontentbytags#10]
I don't know why or how but Bolt shows the following error message:

Extension package xiaohutai/bolt-relatedcontentbytags has an invalid class 'Bolt\Extension\Xiaohutai\RelatedContentByTags\RelatedContentByTagsExtension' and has been skipped.

Bolt 3.1.2 gave error pages, updated to Bolt 3.2.1 and now pages that use the {{ relatedcontentbytags(record) }} tag load normally but the extension doesn't work anymore.

**Comment by xiaohutai** [comment]
Hi @peterboorsma, is still an issue?

I'm testing with Bolt 3.2.6 and nothing seems to break for me.
