### ISSUE TITLE
Extension not working on Bolt 3.2.2

### ISSUE THREAD

**Issue by jackiboy** [xiaohutai/bolt-relatedcontentbytags#11]
Hi!
I am trying to use your extension in bolt 3.2.2 but I get the following error message when I add in the twig markup **{{ relatedcontentbytags(record) }}**

An exception has been thrown during the rendering of a template ("Notice: Array to string conversion") in "partials/track/_trackProductModal.twig" at line 11.

**Comment by xiaohutai** [comment]
Hi,

I think it might be because the errors have been more strict by default in newer Bolt versions.
Haven't had the time to fiddle around with the new Bolt yet. Hopefully soon.

**Comment by xiaohutai** [comment]
Hi @jackiboy , is still an issue?

I'm testing with Bolt 3.2.6 and nothing seems to break for me.
