### ISSUE TITLE
Typo in documentation?

### ISSUE THREAD

**Issue by doenietzomoeilijk** [xiaohutai/bolt-relatedcontentbytags#5]
In the readme, it states:

> Default usage:
> 
> ```
> {{ relatedcontentbytype(record) }}
> ```

This, however, results in an error for me, since that function isn't registered in Twig, or for that matter, present in the extension.

Am I missing anything?

**Comment by xiaohutai** [comment]
Ahhh yeah, it should be `relatedcontentbytags`. Thanks for noticing.
