### ISSUE TITLE
Update to Bolt v3 specifications

### ISSUE THREAD

**Issue by nbehier** [xiaohutai/bolt-relatedcontentbytags#6]
Is there already some work done to transform that extension to Bolt v3 ?

**Comment by xiaohutai** [comment]
Hi @nbehier , not at the moment. I believe it shouldn't be too hard to convert this for Bolt 2 or 3. However, Bolt 3 may have some changes in functions that need to be called differently now.

**Comment by nbehier** [comment]
As soon as possible, I should try to convert this extension to Bolt v3.

**Comment by nbehier** [comment]
@xiaohutai I could send the new version (for Bolt v3) this evening. How do you want to manage branches : one for `bolt-v2` and get new version on `master` ?

**Comment by xiaohutai** [comment]
It should be okay like this. If there are necessary bugfixes for the old version, then we can branch.
