### ISSUE TITLE
[BUG] v3.0.0 not satisfi

### ISSUE THREAD

**Issue by nbehier** [xiaohutai/bolt-relatedcontentbytags#9]
- Relevant Extension Version: **3.0.0**
  - Relevant Bolt Version: **3.0.8**
  - Install type: **Bolt Admin Extension Page**
  - PHP version: **5.6**
  - Used webserver: **Apache**

When I try to install extension en v3.0.0, I get a PHP Error : _Could not find package xiaohutai/bolt-relatedcontentbytags at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
File: /vendor/bolt/bolt/src/Composer/Action/BaseAction.php::198_

![160721_relatedplugin-error](https://cloud.githubusercontent.com/assets/1059917/17016941/a608a976-4f31-11e6-9266-1f7c55e6f112.PNG)

I'll try as soon as possible to check with a Bolt v3.0.11 to check if I get the same error.

**Comment by xiaohutai** [comment]
Odd. It works for me. Using the same setup as you, but using Bolt `3.0.10`.

**Comment by nbehier** [comment]
So weird... I try again, and it works perfectly on the same environment (Bolt v3.0.8) :-(
